spring.application.name=demo

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

file.upload-dir=uploads

#spring.jpa.hibernate.ddl-auto=update

####################################
# Gemini API Configuration
####################################
gemini.api-key=${GEMINI_API_KEY}
gemini.chat-model=gemini-2.0-flash
gemini.embedding-model=embedding-001


####################################
# RAG Configuration
####################################
rag.similarity.threshold=0.30
rag.top-k=5
