spring.application.name=demo

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

file.upload-dir=uploads

#spring.jpa.hibernate.ddl-auto=update

ollama.base-url=http://localhost:11434
ollama.embedding-model=nomic-embed-text


####################################
# RAG Configuration
####################################
rag.similarity.threshold=0.75
rag.top-k=5
